### ISSUE TITLE
Missing hook

### ISSUE THREAD

**Issue by kelu124** [echopen/the_trove#2]
Yop @Aurelie-Mutschler 
It seems that the hook between the repo and the gitbook is not on - and I can't put it in place. Is there anything you can do?
Thanks!

**Comment by Aurelie-Mutschler** [comment]
the gitbook is synced with the repo. the update from your commits didn't work because you have to put a readme.md at the root of the repo. you might be able to check it by yourself at https://www.gitbook.com/book/echopen/the_trove/activity
